#!/bin/python3
import random
print ('''Password Generator
=============================
''')

chars = 'hjuywqsert!@#&^%QPEWSFG'

number = input ('number of passwords?')
number = int (number)

length= input('password length?')
length= int(length)

print ('\nhere are your passwords:')

for p in range(number):
    password= ''
    for c in range(length):
      password += random.choice(chars)
    print(password)
 
